version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./local.env
    volumes:
      - ./:/go/src/github.com/silinternational/serverless-google-groups-sync
    working_dir: /go/src/github.com/silinternational/serverless-google-groups-sync
    command: ["./run-debug.sh"]