# For full config options, check the docs:
#    docs.serverless.com

service: serverless-google-groups-sync

provider:
  name: aws
  runtime: go1.x
  timeout: 120
  versionFunctions: false
  memorySize: 128
  vpc:
    securityGroupIds:
      - ${env:VPC_SG_ID}
    subnetIds:
      - ${env:VPC_SUBNET1}
      - ${env:VPC_SUBNET2}
      - ${env:VPC_SUBNET3}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "*"

    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"

  # you can overwrite defaults here
  #  stage: dev
  region: us-east-1

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}
    S3_BUCKET_FOR_GROUPS_MAP: ${env:S3_BUCKET_FOR_GROUPS_MAP}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}


package:
  exclude:
  - ./**
  include:
  - ./bin/**

functions:
  cron:
    handler: bin/testlambda
    events:
    - schedule: cron(*/30 * * * ? *) # every 3 minutes


resources:
  Resources:
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET_FOR_GROUPS_MAP}
        AccessControl: Private


  # Print out the name of the bucket that is created
  Outputs:
    ConfigBucketName:
      Value:
        Ref: ConfigBucket
    ConfigBucketARN:
      Value:
        "Fn::GetAtt": [ ConfigBucket, Arn ]